[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.4.8"
itertools = "0.12.0"
log = "0.4.20"
once_cell = "1.18.0"
priority-queue = "1.3.2"
regex = "1.10.2"
simple_logger = "4.3.0"
